### ISSUE TITLE
application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by NaiimAb** [teticio/lambda-scraper#11]
Hello, 
thank you for this awesome library. is there a way to use with with application/x-www-form-urlencoded post? I used and I'm getting
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}

**Comment by teticio** [comment]
Hi! Yes, I believe so. The `x-` headers are stripped out because they interfere with AWS but if you precede them with `lambda-scraper-` as per the README, they should get passed to your final endpoint unadulterated.
