### ISSUE TITLE
confused on how to use the scraper

### ISSUE THREAD

**Issue by josephknutson5** [teticio/lambda-scraper#3]

**Comment by josephknutson5** [comment]
i've watched some tutorials and figured out how github, terraform, etc., functions, but im getting an error. let me know if you have any idea what i can do about it.
![error](https://user-images.githubusercontent.com/105376397/167893456-42f293bf-38aa-4966-a1ca-668899a9477b.PNG)

**Comment by daVinci13** [comment]
> i've watched some tutorials and figured out how github, terraform, etc., functions, but im getting an error. let me know if you have any idea what i can do about it. ![error](https://user-images.githubusercontent.com/105376397/167893456-42f293bf-38aa-4966-a1ca-668899a9477b.PNG)

Edit main.tf and change **version = "=4.9"**

**Comment by teticio** [comment]
Try now. I had pinned a version which is now incompatible with some other package. Let me know if that sorts it. Thanks
