### ISSUE TITLE
KeyError: 'body'

### ISSUE THREAD

**Issue by togersonS** [teticio/lambda-scraper#7]
Traceback (most recent call last):
  File "test_scraper.py", line 46, in <module>
    response = proxy.send('https://ipinfo.io/ip')
  File "test_scraper.py", line 37, in get_proxy
    response['body'] = b64decode(response['body'])
KeyError: 'body'

**Comment by teticio** [comment]
try printing out the response - there may be a clue there. You can also check the cloudwatch logs in the console.

**Comment by Rangorio** [comment]
I am having the same issue

**Comment by teticio** [comment]
It may not be the same error, but thanks for the log. I did find this https://stackoverflow.com/questions/76579248/unable-to-import-module-lambda-function-cannot-import-name-etree-from-lxml#:~:text=1%20Answer&text=This%20is%20happening%20because%20lxml,is%20(Amazon%20Linux%202). but I am unable to reproduce this problem with my code as it stands. Did you change anything in the configuration? Which region are you deploying to? Also, what version of terraform are you using? I'd be grateful for more info, because it may effect more people.

**Comment by teticio** [comment]
Please pull the latest version and consult the README. If you run terraform in Docker as suggested, it should work. Please let me know if this solves your problem. Thanks

**Comment by teticio** [comment]
Actually i couldn't get this approach to work on the Mac M1, so I decided to change the Lambda function to build in Docker, as opposed to building the layer locally. This is much faster, simpler and works cross platform. I've tested it on a Mac M1 and it works. (Remember to pull again.)

Thanks again for taking the time to report the issue with helpful logs.

**Comment by Rangorio** [comment]
> It may not be the same error, but thanks for the log. I did find this https://stackoverflow.com/questions/76579248/unable-to-import-module-lambda-function-cannot-import-name-etree-from-lxml#:~:text=1%20Answer&text=This%20is%20happening%20because%20lxml,is%20(Amazon%20Linux%202). Are you by any chance running on a Mac? I will see if I can reproduce the problem on my Mac book. It hadn't occured to me that there could be a cross platform issue. (All the more reason not to use Macs, but hey.)

Yes i am using Mac

**Comment by Rangorio** [comment]
Yes it is working now but i needed to change memory_size to 3008 
`module "lambda_proxy" {
  source         = "terraform-aws-modules/lambda/aws"
  count          = var.num_proxies
  function_name  = "proxy-${count.index}"
  create_package = false
  image_uri      = module.docker_image.image_uri
  package_type   = "Image"
  architectures  = ["x86_64"]
  timeout        = 180
  memory_size    = 3008
  hash_extra     = count.index
}` 
else it was giving error `Error: creating Lambda Function (proxy-8): operation error Lambda: CreateFunction, https response error StatusCode: 400, RequestID: bd606fe0-8d18-43cc-a86c-ff69fd9bb1a2, api error ValidationException: 'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 300`

**Comment by Rangorio** [comment]
Btw thanks alot brother

**Comment by teticio** [comment]
Great! Btw, I just added a similar repo that uses selenium for cases that cannot be handled with requests. Check it out (lambda-selenium).

**Comment by Rangorio** [comment]
> Great! Btw, I just added a similar repo that uses selenium for cases that cannot be handled with requests. Check it out (lambda-selenium).

Sure will check it out
